# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # This is a full desktop box for Ubuntu Precise
  config.vm.box = "box-cutter/ubuntu1204-desktop"

  # ROS Hydro full desktop is installed by a very simple shell script
  config.vm.provision :shell, path: "http://github.com/encs-humanoid/devops/provision/build_hydro_full.sh"

end
